project_id = "olqsevymcwokwnfbswxh"

[functions.port-scan]
verify_jwt = false

[functions.analyze-scan]
verify_jwt = false

[functions.generate-scan-report]
verify_jwt = false

[functions.rss-proxy]
verify_jwt = false

[functions.shodan-proxy]
verify_jwt = false