import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const body = await req.json().catch(() => ({}));
    const isTest = body?.test === true;

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // 1. Load watchlist
    const { data: watchlistItems } = await supabase
      .from("watchlist")
      .select("*")
      .eq("active", true);

    if (!watchlistItems || watchlistItems.length === 0) {
      return new Response(JSON.stringify({ success: true, message: "No active watchlist items", matches: [] }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // 2. Load notification config
    const { data: notifyConfig } = await supabase
      .from("app_settings")
      .select("value")
      .eq("key", "watchlist_notifications")
      .single();

    const config = (notifyConfig?.value as any) || { enabled: false, recipients: "", frequency: "daily", method: "email" };

    if (!config.enabled && !isTest) {
      return new Response(JSON.stringify({ success: true, message: "Watchlist notifications are disabled", matches: [] }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // 3. Fetch recent posts from RansomLook API
    const rlResponse = await fetch("https://www.ransomlook.io/api/last/7", {
      headers: { "Accept": "application/json" },
    });

    let posts: any[] = [];
    if (rlResponse.ok) {
      const rawData = await rlResponse.json();
      // Flatten the nested structure: { "groupname": [posts] }
      if (typeof rawData === "object" && !Array.isArray(rawData)) {
        for (const [groupName, groupPosts] of Object.entries(rawData)) {
          if (Array.isArray(groupPosts)) {
            for (const post of groupPosts) {
              posts.push({
                group_name: groupName,
                post_title: post.post_title || "",
                discovered: post.discovered || "",
                website: post.website || "",
              });
            }
          }
        }
      } else if (Array.isArray(rawData)) {
        posts = rawData;
      }
    }

    // 4. Match watchlist orgs against posts
    const matches: any[] = [];
    for (const item of watchlistItems) {
      const orgLower = item.organization.toLowerCase();
      const matchedPosts = posts.filter(p => {
        const title = (p.post_title || "").toLowerCase();
        const website = (p.website || "").toLowerCase();
        return title.includes(orgLower) || website.includes(orgLower);
      });
      if (matchedPosts.length > 0) {
        matches.push({
          organization: item.organization,
          posts: matchedPosts.slice(0, 10),
          count: matchedPosts.length,
        });
      }
    }

    // 5. Send notifications if there are matches
    let notificationSent = false;
    if (matches.length > 0 && config.recipients?.trim()) {
      const recipients = config.recipients.split(/[,;\s]+/).filter((r: string) => r.includes("@"));
      
      if (recipients.length > 0 && config.method === "email") {
        // Load SMTP config
        const { data: intSettings } = await supabase
          .from("app_settings")
          .select("value")
          .eq("key", "integrations")
          .single();

        const smtp = (intSettings?.value as any)?.smtp;
        if (smtp?.host && smtp?.password) {
          // Build email body
          const subject = `🚨 RansomLook Alert: ${matches.length} watchlist organization(s) detected in leak data`;
          let emailBody = `<h2>RansomLook Watchlist Alert</h2>`;
          emailBody += `<p>The following watched organizations were found in recent ransomware leak posts:</p>`;
          
          for (const match of matches) {
            emailBody += `<h3>🔴 ${match.organization} (${match.count} post(s))</h3><ul>`;
            for (const post of match.posts) {
              emailBody += `<li><strong>${post.group_name}</strong>: ${post.post_title || "Unknown"} — ${post.discovered ? new Date(post.discovered).toLocaleDateString() : "Unknown date"}</li>`;
            }
            emailBody += `</ul>`;
          }
          emailBody += `<hr><p style="color:#888;font-size:12px;">This alert was generated by your ThreatIntel watchlist monitoring.</p>`;

          // Send via send-email function
          try {
            const anonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
            const emailResp = await fetch(`${supabaseUrl}/functions/v1/send-email`, {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${anonKey}`,
              },
              body: JSON.stringify({
                to: recipients,
                subject,
                body: emailBody,
                smtpConfig: smtp,
              }),
            });
            if (emailResp.ok) notificationSent = true;
          } catch (e) {
            console.error("Failed to send watchlist email:", e);
          }
        }
      }

      // Webhook notification
      if (config.method === "webhook") {
        const { data: genSettings } = await supabase
          .from("app_settings")
          .select("value")
          .eq("key", "general")
          .single();
        const webhookUrl = (genSettings?.value as any)?.webhookUrl;
        if (webhookUrl) {
          try {
            await fetch(webhookUrl, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                type: "ransomlook_watchlist_alert",
                matches,
                timestamp: new Date().toISOString(),
              }),
            });
            notificationSent = true;
          } catch (e) {
            console.error("Failed to send webhook:", e);
          }
        }
      }
    }

    // 6. Log to audit
    if (matches.length > 0) {
      await supabase.from("audit_log").insert({
        action: "watchlist_check",
        entity_type: "watchlist",
        details: {
          matches_count: matches.length,
          organizations: matches.map(m => m.organization),
          notification_sent: notificationSent,
          is_test: isTest,
        },
      });
    }

    return new Response(JSON.stringify({
      success: true,
      message: matches.length > 0
        ? `Found ${matches.length} watchlist match(es)${notificationSent ? " — notification sent" : ""}`
        : "No matches found in recent leak data",
      matches,
      notification_sent: notificationSent,
      posts_checked: posts.length,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("watchlist-check error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
