import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

interface FeedItem {
  id: string;
  title: string;
  link: string;
  description: string;
  pubDate: string;
  feedName?: string;
  feedId?: string;
}

const SEVERITY_LEVELS: Record<string, number> = {
  critical: 5, high: 4, medium: 3, low: 2, info: 1,
};

function estimateSeverity(title: string, description: string): string {
  const text = `${title} ${description}`.toLowerCase();
  const criticalTerms = ["critical", "rce", "remote code execution", "zero-day", "0-day", "actively exploited", "emergency", "ransomware attack", "supply chain"];
  const highTerms = ["high", "exploit", "vulnerability", "cve-", "privilege escalation", "authentication bypass", "data breach", "malware"];
  const mediumTerms = ["medium", "moderate", "denial of service", "dos", "xss", "cross-site", "injection", "phishing"];
  const lowTerms = ["low", "minor", "informational", "update", "patch available", "advisory"];

  if (criticalTerms.some(t => text.includes(t))) return "critical";
  if (highTerms.some(t => text.includes(t))) return "high";
  if (mediumTerms.some(t => text.includes(t))) return "medium";
  if (lowTerms.some(t => text.includes(t))) return "low";
  return "info";
}

function meetsThreshold(itemSeverity: string, threshold: string): boolean {
  return (SEVERITY_LEVELS[itemSeverity] || 0) >= (SEVERITY_LEVELS[threshold] || 0);
}

function extractTag(xml: string, tag: string): string {
  const cdataRegex = new RegExp(`<${tag}[^>]*>\\s*<!\\[CDATA\\[([\\s\\S]*?)\\]\\]>\\s*</${tag}>`, "i");
  const cdataMatch = xml.match(cdataRegex);
  if (cdataMatch) return cdataMatch[1].trim();
  const regex = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`, "i");
  const match = xml.match(regex);
  return match ? match[1].trim().replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1") : "";
}

function parseRSSItems(xml: string): FeedItem[] {
  const items: FeedItem[] = [];
  const itemRegex = /<item[\s>]([\s\S]*?)<\/item>|<entry[\s>]([\s\S]*?)<\/entry>/gi;
  let match;
  while ((match = itemRegex.exec(xml)) !== null) {
    const block = match[1] || match[2] || "";
    const title = extractTag(block, "title");
    const link = extractTag(block, "link") || extractTag(block, "guid");
    const description = extractTag(block, "description") || extractTag(block, "summary");
    const pubDate = extractTag(block, "pubDate") || extractTag(block, "published") || extractTag(block, "updated");
    if (title) {
      items.push({
        id: link || `${title}-${pubDate}`,
        title: title.replace(/<[^>]*>/g, ""),
        link: link.replace(/<[^>]*>/g, ""),
        description: description.replace(/<[^>]*>/g, "").substring(0, 500),
        pubDate,
      });
    }
  }
  return items;
}

async function fetchFeed(url: string): Promise<FeedItem[]> {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 15000);
    const res = await fetch(url, {
      headers: { "User-Agent": "ThreatFeed/1.0", "Accept": "application/rss+xml, application/xml, text/xml, */*" },
      signal: controller.signal,
    });
    clearTimeout(timeout);
    if (!res.ok) return [];
    const xml = await res.text();
    return parseRSSItems(xml);
  } catch {
    return [];
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const sb = createClient(supabaseUrl, supabaseKey);

    // Load settings
    const { data: settingsRows } = await sb.from("app_settings").select("key, value");
    const generalSettings = settingsRows?.find(r => r.key === "general")?.value as any || {};
    const integrationSettings = settingsRows?.find(r => r.key === "integrations")?.value as any || {};

    const globalThreshold = generalSettings.severityThreshold || "high";
    const alertFooterText = generalSettings.alertFooterText || "Generated by Threat Intelligence Platform — Alert Monitoring";
    const smtpConfig = integrationSettings.smtp;

    // Parse recipients
    const recipientStr = generalSettings.alertRecipients || smtpConfig?.from || "";
    const recipients = recipientStr.split(/[,;\s]+/).map((r: string) => r.trim()).filter(Boolean);

    if (recipients.length === 0) {
      return new Response(JSON.stringify({ success: false, error: "No alert recipients configured" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Load alert rules
    const { data: rules } = await sb.from("alert_rules").select("*").eq("active", true);
    if (!rules || rules.length === 0) {
      return new Response(JSON.stringify({ success: true, message: "No active alert rules", matches: 0 }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Load feed sources
    const { data: sources } = await sb.from("feed_sources").select("id, name, url, active").eq("active", true);
    const sourceUrlMap = new Map<string, string>();
    for (const src of (sources || [])) {
      sourceUrlMap.set(src.id, src.url);
    }

    // Fetch all configured feeds
    const allItems: FeedItem[] = [];
    const feedPromises = (sources || []).map(async (src) => {
      const items = await fetchFeed(src.url);
      for (const item of items) {
        item.feedName = src.name;
        item.feedId = src.id;
      }
      return items;
    });

    // Fetch external URLs from rules
    const externalUrls = new Set<string>();
    for (const rule of rules) {
      if (!rule.url_pattern?.trim()) continue;
      const pattern = rule.url_pattern.trim();
      const matchesConfigured = (sources || []).some((src: any) =>
        src.url.toLowerCase().includes(pattern.toLowerCase()) ||
        pattern.toLowerCase().includes(src.url.toLowerCase())
      );
      if (!matchesConfigured && (pattern.startsWith("http://") || pattern.startsWith("https://"))) {
        externalUrls.add(pattern);
      }
    }

    const externalPromises = Array.from(externalUrls).map(async (url) => {
      const items = await fetchFeed(url);
      for (const item of items) {
        item.feedName = url;
        item.feedId = url;
      }
      return items;
    });

    const allResults = await Promise.all([...feedPromises, ...externalPromises]);
    for (const items of allResults) {
      allItems.push(...items);
    }

    // Filter to today's items
    const today = new Date().toDateString();
    const todayFeeds = allItems.filter(f => f.pubDate && new Date(f.pubDate).toDateString() === today);

    // Match against rules
    const matched: { item: FeedItem; severity: string; matchedRules: string[] }[] = [];

    for (const feed of todayFeeds) {
      const severity = estimateSeverity(feed.title, feed.description);
      if (!meetsThreshold(severity, globalThreshold)) continue;

      const matchedRuleNames: string[] = [];
      for (const rule of rules) {
        if (!meetsThreshold(severity, rule.severity_threshold)) continue;

        if (rule.url_pattern && rule.url_pattern.trim() !== "") {
          const pattern = rule.url_pattern.toLowerCase().trim();
          const feedSourceUrl = sourceUrlMap.get(feed.feedId || "")?.toLowerCase() || (feed.feedId || "").toLowerCase();
          const feedLink = (feed.link || "").toLowerCase();
          const feedName = (feed.feedName || "").toLowerCase();
          const matches = feedSourceUrl.includes(pattern) || pattern.includes(feedSourceUrl) ||
            feedLink.includes(pattern) || feedName.includes(pattern) || (feed.feedId || "").toLowerCase() === pattern;
          if (!matches) continue;
        }

        const hasKeyword = (rule.keywords as string[]).length === 0 || (rule.keywords as string[]).some((kw: string) =>
          feed.title.toLowerCase().includes(kw.toLowerCase()) ||
          feed.description.toLowerCase().includes(kw.toLowerCase())
        );
        if (hasKeyword) matchedRuleNames.push(rule.name);
      }

      if (matchedRuleNames.length > 0) {
        matched.push({ item: feed, severity, matchedRules: matchedRuleNames });
      }
    }

    if (matched.length === 0) {
      return new Response(JSON.stringify({ success: true, message: "No matches found", matches: 0 }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Sort by severity
    matched.sort((a, b) => (SEVERITY_LEVELS[b.severity] || 0) - (SEVERITY_LEVELS[a.severity] || 0));

    // Build HTML email
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto;">
        <h2 style="color: #dc2626; border-bottom: 2px solid #dc2626; padding-bottom: 8px;">
          🚨 Alert Monitoring — ${matched.length} Threat(s) Detected
        </h2>
        <p style="color: #666; font-size: 13px;">Automated Scan — ${new Date().toLocaleString()} | Threshold: ≥${globalThreshold}</p>
        ${matched.map(r => `
          <div style="border: 1px solid ${r.severity === 'critical' ? '#dc2626' : r.severity === 'high' ? '#ea580c' : '#ca8a04'}; border-radius: 8px; padding: 16px; margin: 12px 0; background: ${r.severity === 'critical' ? '#fef2f2' : r.severity === 'high' ? '#fff7ed' : '#fefce8'};">
            <span style="display: inline-block; background: ${r.severity === 'critical' ? '#dc2626' : r.severity === 'high' ? '#ea580c' : '#ca8a04'}; color: white; font-size: 11px; padding: 2px 8px; border-radius: 4px; text-transform: uppercase; font-weight: bold;">${r.severity}</span>
            <h3 style="margin: 8px 0 4px; font-size: 15px;">${r.item.title}</h3>
            <p style="color: #666; font-size: 12px; margin: 4px 0;">Source: ${r.item.feedName || 'Unknown'} • ${r.item.pubDate ? new Date(r.item.pubDate).toLocaleDateString() : '—'}</p>
            <p style="font-size: 13px; color: #333; margin: 8px 0;">${(r.item.description || '').substring(0, 300)}${(r.item.description || '').length > 300 ? '...' : ''}</p>
            <p style="font-size: 11px; color: #888;">Matched Rules: ${r.matchedRules.join(', ')}</p>
            ${r.item.link ? `<a href="${r.item.link}" style="color: #2563eb; font-size: 12px;">View Details →</a>` : ''}
          </div>
        `).join('')}
        <p style="color: #999; font-size: 11px; margin-top: 24px; border-top: 1px solid #eee; padding-top: 8px;">
          ${alertFooterText}
        </p>
      </div>
    `;

    // Send email via send-email function
    if (smtpConfig?.host && smtpConfig?.username && smtpConfig?.password && smtpConfig?.from) {
      const emailResponse = await fetch(`${supabaseUrl}/functions/v1/send-email`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${supabaseKey}`,
        },
        body: JSON.stringify({
          to: recipients,
          subject: `🚨 Alert: ${matched.length} threat(s) detected — ${new Date().toLocaleDateString()}`,
          body: htmlBody,
          smtpConfig,
        }),
      });

      const emailResult = await emailResponse.json();

      // Log to email_log
      try {
        await sb.from("email_log").insert({
          recipients,
          subject: `🚨 Alert: ${matched.length} threat(s) detected — ${new Date().toLocaleDateString()}`,
          body: htmlBody,
          status: emailResult.success ? "sent" : "failed",
          error_message: emailResult.error || null,
        });
      } catch (logErr) {
        console.error("Failed to log email:", logErr);
      }

      // Log to audit_log
      try {
        await sb.from("audit_log").insert({
          entity_type: "alert_scan",
          action: "automated_scan",
          details: { matches: matched.length, recipients, emailSent: emailResult.success },
        });
      } catch {}

      return new Response(JSON.stringify({
        success: true,
        matches: matched.length,
        emailSent: emailResult.success,
        recipients,
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({
      success: true,
      matches: matched.length,
      emailSent: false,
      error: "SMTP not configured",
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (e: any) {
    console.error("alert-scan error:", e);
    return new Response(JSON.stringify({ error: e.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
